// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqe5a3movJbmZbwHZZDeqhIhWBk1HLOqg',
    appId: '1:169016250621:web:7fc034553a462e8489ee94',
    messagingSenderId: '169016250621',
    projectId: 'apk-encrypt-d9254',
    authDomain: 'apk-encrypt-d9254.firebaseapp.com',
    databaseURL: 'https://apk-encrypt-d9254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apk-encrypt-d9254.firebasestorage.app',
    measurementId: 'G-60Q2R4PZ6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkDOqCIa9Sc8S2wP1-GRQ_HFGu1PWSKWc',
    appId: '1:385810867710:android:3c565158bf3bc0696f8caf',
    messagingSenderId: '385810867710',
    projectId: 'tomas-app-7a613',
    storageBucket: 'tomas-app-7a613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY_uKrkmG-201F6O0BXdAhlbGuv5TlLjo',
    appId: '1:169016250621:ios:2a24c16adfb7bdd389ee94',
    messagingSenderId: '169016250621',
    projectId: 'apk-encrypt-d9254',
    databaseURL: 'https://apk-encrypt-d9254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apk-encrypt-d9254.firebasestorage.app',
    iosBundleId: 'com.tomas.tomasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY_uKrkmG-201F6O0BXdAhlbGuv5TlLjo',
    appId: '1:169016250621:ios:2a24c16adfb7bdd389ee94',
    messagingSenderId: '169016250621',
    projectId: 'apk-encrypt-d9254',
    databaseURL: 'https://apk-encrypt-d9254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apk-encrypt-d9254.firebasestorage.app',
    iosBundleId: 'com.tomas.tomasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqe5a3movJbmZbwHZZDeqhIhWBk1HLOqg',
    appId: '1:169016250621:web:eec9a1b7f983482289ee94',
    messagingSenderId: '169016250621',
    projectId: 'apk-encrypt-d9254',
    authDomain: 'apk-encrypt-d9254.firebaseapp.com',
    databaseURL: 'https://apk-encrypt-d9254-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'apk-encrypt-d9254.firebasestorage.app',
    measurementId: 'G-5Q2M3HPXZ3',
  );
}